## Lecture 10 - Modules II

### CSV Module

In [ ]:
import csv   #import csv module

#### Reading CSV Files

In [ ]:
with open('data.csv') as csvfile:    #open csv file (download file from moodle)
    csvreader = csv.reader(csvfile,delimiter=',')  #csv reader object
    for row in csvreader:
        print(row[1])
        print(row)                  #print the csv file row by row (each row is a list of strings, including the header)

Bundesland
['Datum', 'Bundesland', 'BundeslandID', 'AnzEinwohner']
Burgenland
['26.02.20', 'Burgenland', '1', '294436']
Kaernten
['26.02.20', 'Kaernten', '2', '561293']
Niederoesterreich
['26.02.20', 'Niederoesterreich', '3', '1684287']
Oberoesterreich
['26.02.20', 'Oberoesterreich', '4', '149027926.02.20', 'Salzburg', '5', '560643']
Tirol
['26.02.20', 'Tirol', '6', '760161']


In [ ]:
spreadsheet = []
with open('data.csv') as csvfile:
    csvreader = csv.DictReader(csvfile,delimiter=',')   #reads csv file as a list of dictionaries
    for row in csvreader:           #each row is a dictionary (key is column name, value is value in row)
        spreadsheet.append(row)

print(spreadsheet)         #print list of dictionaries
print()

for entry in spreadsheet:       #traverse all dictionaries in the list
    print(entry['BundeslandID'])   #print all entries with key 'Bundesland'


[{'Datum': '26.02.20', 'Bundesland': 'Burgenland', 'BundeslandID': '1', 'AnzEinwohner': '294436'}, {'Datum': '26.02.20', 'Bundesland': 'Kaernten', 'BundeslandID': '2', 'AnzEinwohner': '561293'}, {'Datum': '26.02.20', 'Bundesland': 'Niederoesterreich', 'BundeslandID': '3', 'AnzEinwohner': '1684287'}, {'Datum': '26.02.20', 'Bundesland': 'Oberoesterreich', 'BundeslandID': '4', 'AnzEinwohner': '149027926.02.20', None: ['Salzburg', '5', '560643']}, {'Datum': '26.02.20', 'Bundesland': 'Tirol', 'BundeslandID': '6', 'AnzEinwohner': '760161'}]

1
2
3
4
6


In [ ]:
data = []
with open('data.csv') as csvfile:
    reader = csv.reader(csvfile,delimiter=',')
    for row in reader:        #each row is a list of Strings
        data.append(row)      #data is a list of lists (2-dimensional array)

print(data)                   #print list of lists
print()

for i in range(len(data)):          #traverse all lists in data
    for j in range(len(data[i])):   #for each list traverse all elements
         print(data[i][j])          #print each element

[['Datum', 'Bundesland', 'BundeslandID', 'AnzEinwohner'], ['26.02.20', 'Burgenland', '1', '294436'], ['26.02.20', 'Kärnten', '2', '561293'], ['26.02.20', 'Niederösterreich', '3', '1684287'], ['26.02.20', 'Oberösterreich', '4', '149027926.02.20', 'Salzburg', '5', '560643'], ['26.02.20', 'Tirol', '6', '760161']]

Datum
Bundesland
BundeslandID
AnzEinwohner
26.02.20
Burgenland
1
294436
26.02.20
Kärnten
2
561293
26.02.20
Niederösterreich
3
1684287
26.02.20
Oberösterreich
4
149027926.02.20
Salzburg
5
560643
26.02.20
Tirol
6
760161


#### Writing CSV Files

In [ ]:
with open('data.csv', 'a') as csvfile:
    writer = csv.writer(csvfile,delimiter=',')    #csv writer object
    writer.writerow(['26.02.20', 'Salzburg', '5', '560643'])   #add rows to csv file
    writer.writerow(['26.02.20', 'Tirol', '6', '760161'])

with open('data.csv') as csvfile:    #open csv file
    csvreader = csv.reader(csvfile,delimiter=',')  #csv reader object
    for row in csvreader:
        print(row)

['Datum', 'Bundesland', 'BundeslandID', 'AnzEinwohner']
['26.02.20', 'Burgenland', '1', '294436']
['26.02.20', 'Kärnten', '2', '561293']
['26.02.20', 'Niederösterreich', '3', '1684287']
['26.02.20', 'Oberösterreich', '4', '149027926.02.20', 'Salzburg', '5', '560643']
['26.02.20', 'Tirol', '6', '760161']


In [ ]:
data= [{'Datum':'26.02.20', 'Bundesland':'Salzburg', 'BundeslandID':'5', 'AnzEinwohner':'560643'}, {'Datum':'26.02.20', 'Bundesland':'Tirol', 'BundeslandID':'6', 'AnzEinwohner':'760161'}]
with open('data-new.csv', 'w') as csvfile:    #a new csv file is created
    fieldnames = ['Datum', 'Bundesland', 'BundeslandID', 'AnzEinwohner']   #header is a list of strings
    writer = csv.DictWriter(csvfile, fieldnames = fieldnames)    #writer for writing dictionaries to the csv file
    writer.writeheader()                                         #write header to the file
    writer.writerow(data[0])    #write rows
    print(data[0])
    writer.writerow(data[1])
    print(data[1])

{'Datum': '26.02.20', 'Bundesland': 'Salzburg', 'BundeslandID': '5', 'AnzEinwohner': '560643'}
{'Datum': '26.02.20', 'Bundesland': 'Tirol', 'BundeslandID': '6', 'AnzEinwohner': '760161'}


#### CSV Example

In [ ]:
spreadsheet = []
with open('data_population.csv') as csvfile:         #read csv file (download file from moodle)
    csvreader = csv.DictReader(csvfile,delimiter=',')    #reader for storing data in dictionary
    for row in csvreader:
        spreadsheet.append(row)                        #list of dictionaries

#print(spreadsheet)                                     #print list of dictionaries
#print()

for entry in spreadsheet:                              #traverse list of dictionaries
    if entry['year'] == '2030':                        #only print entries with '2030' as value for key 'year'
        print(entry)

[{'year': '2021', 'AGE_15_19': '5785', 'AGE_20_24': '6342', 'AGE_25_29': '6707', 'AGE_30_44': '18690', 'AGE_45_59': '20887'}, {'year': '2022', 'AGE_15_19': '5824', 'AGE_20_24': '6348', 'AGE_25_29': '6824', 'AGE_30_44': '19048', 'AGE_45_59': '20803'}, {'year': '2023', 'AGE_15_19': '5862', 'AGE_20_24': '6487', 'AGE_25_29': '6942', 'AGE_30_44': '19780', 'AGE_45_59': '20792'}, {'year': '2024', 'AGE_15_19': '6004', 'AGE_20_24': '6631', 'AGE_25_29': '7103', 'AGE_30_44': '20711', 'AGE_45_59': '20926'}, {'year': '2025', 'AGE_15_19': '6020', 'AGE_20_24': '6754', 'AGE_25_29': '7168', 'AGE_30_44': '21347', 'AGE_45_59': '20931'}, {'year': '2026', 'AGE_15_19': '6060', 'AGE_20_24': '6765', 'AGE_25_29': '7147', 'AGE_30_44': '21588', 'AGE_45_59': '20855'}, {'year': '2027', 'AGE_15_19': '6108', 'AGE_20_24': '6797', 'AGE_25_29': '7153', 'AGE_30_44': '21914', 'AGE_45_59': '20909'}, {'year': '2028', 'AGE_15_19': '6143', 'AGE_20_24': '6757', 'AGE_25_29': '7155', 'AGE_30_44': '22027', 'AGE_45_59': '20823'},

---

### NumPy Module

In [ ]:
import numpy as np      #import numpy module and use alternative name (np)

#### Creating NumPy arrays

In [ ]:
ar = np.array([1,2,3,4])    #create numpy array with array function
ar2 = np.array([1.5,-2.2,3.7,-4.1])

print(ar)
print(ar2)
print(type(ar))

[1 2 3 4]
[ 1.5 -2.2  3.7 -4.1]
<class 'numpy.ndarray'>


In [ ]:
ar_dim0 = np.array(1)    #array with dimension 0
ar_dim1 = np.array([1,2,3,4])   #array with dimension 1
ar_dim2 = np.array([[1, 2, 3], [4, 5, 6]])  #array with dimension 2 (matrix)

print(ar_dim0)
print()
print(ar_dim1)
print()
print(ar_dim2)


1

[1 2 3 4]

[[1 2 3]
 [4 5 6]]


In [ ]:
array = np.zeros(5)     #create array with 5 elements (all 0)
array2 = np.ones(2)     #create array with 2 elements (all 1)

print(array)
print(array2)

array = np.arange(4, 20)   #create array with values from a to 19
print(array)

array = np.random.rand(5)   #create array with 5 elements (random numbers between 0 and 1)
print(array)

[0. 0. 0. 0. 0.]
[1. 1.]
[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0.80345073 0.57176362 0.55092844 0.40638673 0.0154841 ]


#### Accessing NumPy arrays

In [ ]:
ar_dim1 = np.array([1,2,3,4])
ar_dim2 = np.array([[1, 2, 3], [4, 5, 6]])

print(ar_dim1[0], '-->', ar_dim1[-1])    #first and last element
print(ar_dim2[0, 0], '-->', ar_dim2[0, -1])   #first array first element, first array last element
print(ar_dim2[1, 0], '-->', ar_dim2[1, -1])   #second array first element, second array last element

1 --> 4
1 --> 3
4 --> 6


#### CSV to NumPy

In [ ]:
data = []
with open('data.csv') as csvfile:    #open and read csv file
    csvreader = csv.reader(csvfile,delimiter=',')
    for row in csvreader:
        data.append(row)

np_data = np.array(data)     #store data in numpy array
print(np_data)               #print numpy array

[list(['Datum', 'Bundesland', 'BundeslandID', 'AnzEinwohner'])
 list(['26.02.20', 'Burgenland', '1', '294436'])
 list(['26.02.20', 'Kärnten', '2', '561293'])
 list(['26.02.20', 'Niederösterreich', '3', '1684287'])
 list(['26.02.20', 'Oberösterreich', '4', '149027926.02.20', 'Salzburg', '5', '560643'])
 list(['26.02.20', 'Tirol', '6', '760161'])]


#### NumPy example

In [ ]:
data = []
with open('data_population.csv') as csvfile:    #open and read csv file
    csvreader = csv.reader(csvfile,delimiter=',')
    for row in csvreader:
        data.append(row)

np_data = np.array(data)     #store data in numpy array
print(np_data)               #print numpy array

[['year' 'AGE_15_19' 'AGE_20_24' 'AGE_25_29' 'AGE_30_44' 'AGE_45_59']
 ['2021' '5785' '6342' '6707' '18690' '20887']
 ['2022' '5824' '6348' '6824' '19048' '20803']
 ['2023' '5862' '6487' '6942' '19780' '20792']
 ['2024' '6004' '6631' '7103' '20711' '20926']
 ['2025' '6020' '6754' '7168' '21347' '20931']
 ['2026' '6060' '6765' '7147' '21588' '20855']
 ['2027' '6108' '6797' '7153' '21914' '20909']
 ['2028' '6143' '6757' '7155' '22027' '20823']
 ['2029' '6109' '6773' '7130' '22089' '20768']
 ['2030' '6084' '6722' '7135' '22091' '20756']
 ['2031' '6028' '6708' '7083' '21988' '20685']
 ['2032' '6024' '6754' '7129' '22171' '20809']
 ['2033' '6052' '6832' '7179' '22477' '21044']
 ['2034' '6115' '6852' '7267' '22737' '21328']
 ['2035' '4993' '5214' '5505' '19578' '19834']
 ['2036' '5100' '5476' '5575' '19597' '20513']
 ['2037' '5221' '5734' '5796' '19809' '21222']
 ['2038' '5216' '5842' '5915' '19579' '21630']
 ['2039' '5258' '5941' '6173' '19804' '22141']
 ['2040' '5329' '6069' '6370' '20152'

In [ ]:
print(np_data[1][1])

5785
