# Reading Corner 8 - Python Modules: csv, NumPy


## Reading Corner 1: Processing CSV files

The following small program shows how to create a csv file and insert content (from a list of lists). The file is stored with the name "mycsv.csv". Next, the file is opened, the content is read and printed to the console. The module 'csv' is used, which must be imported before it can be used.

In [ ]:
import csv # Import of the csv module. It provides simple functions such as csv.writer() or csv.reader() which can now be used

In [ ]:
data = [[22,'Lorenz', 1111], [122,'Markus', 344], [222, 'Simone', 15], [1623, 'Bianca', 753], [1238, 'Ludwig', 912]] # Data as a list of lists

with open('mycsv.csv', 'w') as f: #Create a CSV file using the with statement
    writer = csv.writer(f)
    writer.writerows(data)

with open('mycsv.csv','r') as csvfile:   #Open and read a CSV file using the with statement.
    data = csv.reader(csvfile, delimiter=',')
    for row in data:
        print(row)

['22', 'Lorenz', '1111']
['122', 'Markus', '344']
['222', 'Simone', '15']
['1623', 'Bianca', '753']
['1238', 'Ludwig', '912']


---

## Reading Corner 2: NumPy basics

The following examples show how to work with numpy.


In [ ]:
import numpy as np  # Import of the numpy module with the name np

In [ ]:
a1=np.array([1,2,3])     #Creating a 1-dimensional array
a2=np.array([(1,2,3),(4,5,6)])   #Creating a 2-dimensional array
a3=np.zeros(3)              #Creating an array with three zeros
a4=np.zeros([3,2])       #Creating an array with zeros and 3 rows and 2 columns
a5=np.ones([3,4])       #Creating an array with ones and 3 rows and 4 columns


In [ ]:
#Outputs for a1
print('a1:')
print('Form: a1',a1.shape)   #shape returns a tuple with number of rows and number of columns
print('Data type a1:',type(a1))

a1:
Form: a1 (3,)
Data type a1: <class 'numpy.ndarray'>


In [ ]:
#Outputs for a2
print('a2:')
print(a2)
print('Form: a2',a2.shape)
print('a2 has', a2.shape[0], 'rows and', a2.shape[1], 'columns')  #Access to rows and columns via index

a2:
[[1 2 3]
 [4 5 6]]
Form: a2 (2, 3)
a2 has 2 rows and 3 columns


In [ ]:
#Output for a3
print('a3:')
print(a3)
print('Form: a3',a3.shape)

a3:
[0. 0. 0.]
Form: a3 (3,)


In [ ]:
#Output for a4
print('a4:')
print(a4)
print('Form: a4',a4.shape)
print('a4 has', a4.shape[0], 'rows and', a4.shape[1], 'columns')

a4:
[[0. 0.]
 [0. 0.]
 [0. 0.]]
Form: a4 (3, 2)
a4 has 3 rows and 2 columns


In [ ]:
#Output for a5
print('a5:')
print(a5)
print('Form: a5',a5.shape)
print('a5 has', a5.shape[0], 'rows and', a5.shape[1], 'columns')

a5:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Form: a5 (3, 4)
a5 has 3 rows and 4 columns


In [ ]:
#Access operations - Array indices start at 0
print('Access to values a2: ',a2[1][2]) #Access to values of a2 - second row, third column
print('Access to values a2: ',a2[0][1]) #Access to values of a2 - first row, second column
print('Access to values a2: ',a2[0][2]) #Access to values of a2 - first row, third column

Access to values a2:  6
Access to values a2:  2
Access to values a2:  3


In [ ]:
print('Calculations: ', a2.mean(axis=0)) #Average of a2 axis = 0 calculates the averages of the columns
print('Calculations: ', a2.mean(axis=1)) #Average of a2 axis = 1 calculates the averages of the rows
print('Calculations: ', a1.mean(axis=0)) #Average of a1 axis = 0 calculates the averages of the columns

Calculations:  [2.5 3.5 4.5]
Calculations:  [2. 5.]
Calculations:  2.0


In [ ]:
n=np.arange(1,8) #Creating a Numpy array with the values 1 to 7
print('n:',n)

n: [1 2 3 4 5 6 7]


In [ ]:
print('Loop iterations numpy:')
for num in n: # Numpy arrays can also be traversed with loops
    print(num)

Loop iterations numpy:
1
2
3
4
5
6
7


---

## Reading Corner 3: CSV and NumPy

The following examples show reading data from a CSV file and storing that data in a NumPy array.


In [ ]:
data_from_file = []
with open('mycsv.csv','r') as csvfile:   #Open and read the CSV file using the with statement
    data = csv.reader(csvfile, delimiter=',')
    for row in data:
        print(row)
        data_from_file.append(row)


np_data = np.array(data_from_file)  #Create a NumPy array from the data of the CSV file

print()
print(np_data)

sum_val=0

for i in np_data:     #Traversing the array
    sum_val+=int(i[2])    #Summing up the values of the third column (index 2). First, the string value must be converted to an integer value

print()
print(f'Sum:{sum_val}')

['22', 'Lorenz', '1111']
['122', 'Markus', '344']
['222', 'Simone', '15']
['1623', 'Bianca', '753']
['1238', 'Ludwig', '912']

[['22' 'Lorenz' '1111']
 ['122' 'Markus' '344']
 ['222' 'Simone' '15']
 ['1623' 'Bianca' '753']
 ['1238' 'Ludwig' '912']]

Sum:3135
